In [1]:
from google.colab import drive
drive.mount("/content/gdrive")

Mounted at /content/gdrive


In [2]:
%cd /content/drive/MyDrive/Pytorch_deep_learning_master/data/image_color

/content/drive/MyDrive/Pytorch_deep_learning_master/data/image_color


In [4]:
import torch
import cv2
blue = cv2.imread("blue.jpg")
red = cv2.imread("red.jpg")
green = cv2.imread("green.jpg")

In [15]:
blue = torch.Tensor(blue)
red = torch.Tensor(red)
green = torch.Tensor(green)

In [18]:
blue = blue.permute(2,0,1)
red = red.permute(2,0,1)
green = green.permute(2,0,1)

In [20]:
## BGR 순서로 저장되어 있음

print(blue.mean())
print(red.mean())
print(green.mean())

tensor(114.3238)
tensor(55.3940)
tensor(67.3916)


In [35]:
blue.mean(dim=2).mean(dim=1)

tensor([173.8124, 112.5045,  56.6544])

In [36]:
red.mean(dim=2).mean(dim=1)

tensor([ 33.4802,  20.9486, 111.7531])

In [37]:
green.mean(dim=2).mean(dim=1)

tensor([ 59.8616, 110.7323,  31.5809])