1. 모델을 w2 * t_u ** 2 + w1 * t_u + b로 다시 정의하자

   a. 이 모델을 다루기 위해 훈련 루프의 어떤 부분을 변경해야 하나?
      - learning_rate 값을 더 작게 변경 해야한다.

   b. 모델 변경과 무관한 부분은 어디인가?
      - loss_fn과 training_loop는 변경하지 않았다.
   
   c. 훈련 후 손실이 증가하는가 감소하는가?
      - 훈련 후에 손실이 감소하였다.
   
   d. 실제 결과가 좋아졌나 나빠졌나?
      - 기존 결과에 비해 성능이 나빠졌다.

In [1]:
import torch

In [18]:
t_u = torch.tensor([35.7, 55.9, 58.2, 81.9, 56.3, 48.9, 33.9, 21.8, 48.4, 60.4, 68.4])
t_c = torch.tensor([0.5, 14.0, 15.0, 28.0, 11.0, 8.0, 3.0, -4.0, 6.0, 13.0, 21.0])

print(t_u)
print(t_c)

tensor([35.7000, 55.9000, 58.2000, 81.9000, 56.3000, 48.9000, 33.9000, 21.8000,
        48.4000, 60.4000, 68.4000])
tensor([ 0.5000, 14.0000, 15.0000, 28.0000, 11.0000,  8.0000,  3.0000, -4.0000,
         6.0000, 13.0000, 21.0000])


In [26]:
# 모델 변경
def model(t_u, w1, w2, b):
    return w2 * t_u ** 2 + w1 * t_u + b

In [27]:
# loss 값 설정
def loss_fn(t_p, t_c):
    squared_diffs = (t_p - t_c)**2
    return squared_diffs.mean()

In [32]:
import torch.optim as optim
params = torch.tensor([2.0, 1.0, 0.0], requires_grad = True)
learning_rate = 1e-10
optimizer = optim.SGD([params], lr = learning_rate)

In [33]:
def training_loop(n_epochs, optimizer, params, t_u, t_c):
    for epoch in range(1, n_epochs + 1):
        t_p = model(t_u, *params)
        loss = loss_fn(t_p, t_c)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if epoch % 500 == 0:
            print('Epoch %d, Loss %f' % (epoch, float(loss)))
    
    return params



In [34]:
training_loop(
    n_epochs = 3000,
    optimizer = optimizer,
    params = params,
    t_u = t_u,
    t_c = t_c
)    

Epoch 500, Loss 1227263.750000
Epoch 1000, Loss 124741.093750
Epoch 1500, Loss 13246.875977
Epoch 2000, Loss 1971.842285
Epoch 2500, Loss 831.612549
Epoch 3000, Loss 716.294495


tensor([ 1.9838e+00, -2.5955e-02, -2.7141e-04], requires_grad=True)